/*
 * This source file was generated by the Gradle 'init' task
 */
package numericalmethodsapp;
import java.util.Scanner;

import numericalmethodsapp.methods.Bisection;
import numericalmethodsapp.methods.CramersRule;
import numericalmethodsapp.methods.FalsePosition;
import numericalmethodsapp.methods.FixedPoint;
import numericalmethodsapp.methods.GaussSeidel;
import numericalmethodsapp.methods.GaussianElimination;
import numericalmethodsapp.methods.Jacobi;
import numericalmethodsapp.methods.MatrixProduct;
import numericalmethodsapp.methods.NewtonRaphson;
import numericalmethodsapp.methods.Secant;

public class App {
    public static void main(String[] args) {
        //Console muna

        System.out.println("NUMERICAL METHODS\n");
        System.out.println("1. Fixed-Point Iteration Method");
        System.out.println("2. Newton-Raphson Method");
        System.out.println("3. Secant Method");
        System.out.println("4. Bisection Method");
        System.out.println("5. False Position or Regula Falsi Method");
        System.out.println("6. Matrix Product");
        System.out.println("7. Cramer's Rule");
        System.out.println("8. Gaussian Elimination");
        System.out.println("9. Jacobi Method");
        System.out.println("10. Gauss-Seidel Method");
        System.out.println("");
        System.out.print("Enter method: ");

        Scanner input = new Scanner(System.in);
        int choice = input.nextInt();

        switch (choice){
            case 1 -> {
                System.out.println("Fixed-Point Iteration Method");
                FixedPoint.run(input);
            }
            case 2 -> {
                System.out.println("Newton-Raphson Method");
                NewtonRaphson.run(input);
            }
            case 3 -> {
                System.out.println("Secant Method");
                Secant.run(input);
            }
            case 4 -> {
                System.out.println("Bisection Method");
                Bisection.run(input);
            }
            case 5 -> {
                System.out.println("False Position or Regula Falsi Method");
                FalsePosition.run(input);
            }
            case 6 -> {
                System.out.println("Matrix Product");
                MatrixProduct.run(input);
            }
            case 7 -> {
                System.out.println("Cramer's Rule");
                CramersRule.run(input);
            }
            case 8 -> {
                System.out.println("Gaussian Elimination");
                GaussianElimination.run(input);
            }
            case 9 -> {
                System.out.println("Jacobi Method");
                Jacobi.run(input);
            }
            case 10 -> {
                System.out.println("Gauss-Seidel Method");
                GaussSeidel.run(input);
            }
            default -> System.out.println("Invalid input");
        }
        
    }
}
